CREATE TABLE role(
  id INT(11) AUTO_INCREMENT PRIMARY KEY,
  roleName VARCHAR(255) NOT NULL ,
  roleCode VARCHAR(255) NOT NULL ,
  createUserId VARCHAR(255) NOT NULL ,
  createDate DATETIME DEFAULT NULL ,
  remark VARCHAR(255) DEFAULT ""
)ENGINE=InnoDB DEFAULT CHARSET =utf8;